import React from 'react';
import '../styles/globals.css';
import Head from 'next/dist/next-server/lib/head';
import { Header } from '@/components/layouts/Header';
import { AuthProvider } from '@/contexts/auth';
import App, { AppProps, AppContext } from 'next/app';
import styled from 'styled-components';
import { ChakraProvider } from '@chakra-ui/react';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <ChakraProvider>
        <Head>
          <title></title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <script src="https://platform.twitter.com/widgets.js"></script>
        </Head>
        <AuthProvider>
          <Header />
          <ComponentWrapper>
            <Component {...pageProps} />
          </ComponentWrapper>
        </AuthProvider>
      </ChakraProvider>
    </>
  );
}

export default MyApp;

const ComponentWrapper = styled.div`
  min-height: 100vh;
  height: 100vh;
  padding: 124px 24px 0;
`;
